### ISSUE TITLE
UUID changes on every call to Update-KeePassEntry

### ISSUE THREAD

**Issue by markdomansky** [PSKeePass/PoShKeePass#120]
Everytime I call Update-KeePassEntry, it updates the UUID.  This appears to be because I'm passing the group path.  However the group path is required by the Update-KeePassEntry function.

**Comment by jkdba** [comment]
Nice catch, the Set-KPEntry function to check to see if the path provided matches the existing path.

Out of curiosity what are you using the UUID for that this causes you an issue?

**Comment by markdomansky** [comment]
I'm using PowerShell to automatically update administrator passwords across servers.  I do a search to get an existing entry if it exists, then update it with the new password.

In my local copy, I also added two lines to keep a history of the passwords.  I just clone deep the current entry, clear the history in the new copy, then add it to the current history.

**Comment by jkdba** [comment]
@markdomansky, long time coming all issues are resolved. see latest version.
