### ISSUE TITLE
Defender detects PoShKeePass as a Trojan

### ISSUE THREAD

**Issue by BooBob** [PSKeePass/PoShKeePass#137]
PackageManagement\Install-Package : Package 'PoShKeePass' failed to be installed because: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

Trojan:PowerShell/Pklotide.A
Alert level: Severe

Affected items:
containerfile: C:\Program Files\WindowsPowerShell\Modules\PoShKeePass\2.0.4.0\PoShKeePass.psm1

**Comment by jkdba** [comment]
Hi this has already been fixed please install the latest version from the gallery or clone from master.

`Install-module poshkeepass` or `update-module poshkeepass`

**Comment by jkdba** [comment]
See closed issue #132 for more details.
