### ISSUE TITLE
KeePassGroup functions should return objects of type PSKeePass.Group

### ISSUE THREAD

**Issue by wi-fr** [PSKeePass/PoShKeePass#149]
The New-KeePassGroup and Update-KeePassGroup functions return objects of type “KeePassLib.PwGroup”.  

It would be more convenient receiving objects of type “PSKeePass.Group”. This would allow using them directly as input for the Update-KeePassGroup function.

**Comment by jkdba** [comment]
thanks I'll check it out.

**Comment by jkdba** [comment]
included in latest v.2.1.2.4
