### ISSUE TITLE
When running update command - I get the following error 

### ISSUE THREAD

**Issue by SJHarrison1992** [PSKeePass/PoShKeePass#154]
![image](https://user-images.githubusercontent.com/46562010/51742972-300dc180-2093-11e9-8fb5-0f5adf609fce.png)

With this error, if i click abort - it leaves the .kdbx file in a corrupted state
Clicking retry - the function will work correctly as expected 

However this error message appears each time i run the code, i cannot figure out why

here is my script 

```
#New-KeePassDatabaseConfiguration -DatabaseProfileName "TestProfile" -DatabasePath $KeyPassFile -UseMasterKey

$psw = (New-KeePassPassword -UpperCase -LowerCase -Digits -SpecialCharacters -Length 12)
$Keypassword = convertto-securestring $KeyPassMaster -asplaintext -force
$securePassword = New-Object System.Management.Automation.PSCredential $KeyPassfile, $Keypassword

$keePassEntry = Get-KeePassEntry -KeePassEntryGroupPath WCBS/General/Windows/BuildAccounts -Title "VSTS Build Admin" -DatabaseProfileName "TestProfile" -MasterKey $securePassword
Update-KeePassEntry -title "VSTS Build Admin" -UserName "wcbspass\vstsbuildadmin" -KeePassPassword $psw  -KeePassEntryGroupPath "WCBS/General/Windows/BuildAccounts" -KeePassEntry $keePassEntry -DatabaseProfileName "TestProfile" -MasterKey $securePassword -Force
```

As you can see im using variables for some of the information 

Any suggestions on what I can do to stop this from happening?

**Comment by jkdba** [comment]
Hi @SJHarrison1992 can you please include which version of the module you are running and if you know what version of keepass created the database.

**Comment by jkdba** [comment]
closing duplicate #148
