### ISSUE TITLE
New-KPConnection.ps1 ???

### ISSUE THREAD

**Issue by pythongates** [PSKeePass/PoShKeePass#157]
I'm not sure how to use this function. I can create the session but how do I "reuse"  or reference that open connection to read/write to the database?

**Comment by pythongates** [comment]
I suppose the "issue" would be that the wiki needs updating to include the latest functions and a an example how to utilize the New-KPConnection.  

BTW, excellent work on this!  I love this module!!

**Comment by jkdba** [comment]
Hi @pythongates, thanks for bring this up and I am glad you are finding the module useful. 

I will need to double check but I am pretty sure that function was not intended to be exposed. It looks to have been accidentally left part of the module function export section of the manifest (psd1) from testing an up coming feature.

I do have an existing feature in place [#142](https://github.com/PSKeePass/PoShKeePass/issues/142) to add this type of functionality.

**Comment by pythongates** [comment]
I agree with the statement in #142.  That would be very useful!

Great work on this module! Thank you!
