### ISSUE TITLE
For Each? 

### ISSUE THREAD

**Issue by vincent090** [PSKeePass/PoShKeePass#159]
Hi! 

Love the new .Credential function and I have a question. 

Is it possible to do a For Each loop using Get-KeyPassEntry? 

I though it would be awesome if one could go through each entry in a group. So If I wanted to access several credentials/services at once, I could just loop each customer one by one in a group. 

For example - Group name "Customers" (Database/Customers) 

For each Customer in group Customers do X. 

But when I run the group command it gives me all the credentials at once. Would be cool if it would be possible to loop them somehow.

**Comment by jkdba** [comment]
Hi @vincent090,

Thanks for reaching out and using the module. 

I believe what you are asking can be achieved using the built in powershell for each loops. If I am headed the wrong direction let me know.

```powershell
## get all entries in a group with the pscredential object. 
## Then use pass them via the pipe '|" to the built in powershell function Foreach-Object {}
Get-KeePassEntry -KeePassEntryGroupPath 'test/testgroup' -WithCredential -DatabaseProfileName test | ForEach-Object { $kpEntry = $_; <# do something with the the KeePass Entry object #>  }

## or you can store the Entries into a variable and then loop over them many ways
[psobject[]] $kpentries = Get-KeePassEntry -KeePassEntryGroupPath 'test/testgroup' -WithCredential -DatabaseProfileName test

## loop example 1
foreach($entry in $kpentries)
{
    ## do something with $entry in loop
    $entry
}

#loop example 2
for($i = 0; $i -lt $kpentries.count; $i++)
{
    ## do something with $kpentries[$i] in loop
   $kpentries[$i]
}
```

**Comment by vincent090** [comment]
Thanks a bunch! I was thinking the same, but didnt know exactly how. 

Thanks again for a such a quick reply! Also, please update the documentation if possible to include some examples as to include the $username.credential (or .Username etc etc). 

Excellent script! Works way better then delegated access from Microsoft.

Here is how I solved it (Maybe add it as an example?). 


function coolscript {

Write your PS script which should go for all entries in a group

}


Get-KeePassEntry -KeePassEntryGroupPath 'Database/Groupname' -WithCredential -DatabaseProfileName Test2 | ForEach-Object { 
$kpEntry = $_;coolscript
}

**Comment by jkdba** [comment]
@vincent090 Great, I am glad it worked out! I am thinking about more advanced documentation and community collaboration so I will take your request into consideration.
