### ISSUE TITLE
The composite key is invalid

### ISSUE THREAD

**Issue by jbruns2019** [PSKeePass/PoShKeePass#166]
I have Keypass GUI open using same key file and DB just fine but when I try to use this Posh tool on the get-keepassentry cmdlet I get:

```powershell
PS C:\WINDOWS\system32> Get-KeePassEntry -DatabaseProfileName 'KeyAndMasterKeyDB' -AsPlainText
Exception calling "Open" with "3" argument(s): "The composite key is invalid!
Make sure the composite key is correct and try again."
At C:\Program Files\WindowsPowerShell\Modules\PoShKeePass\2.1.3.0\PoShKeePass.psm1:2664 char:9
+         $null = $DatabaseObject.Open($IOInfo, $CompositeKey, $IStatus ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidCompositeKeyException
```

**Comment by jkdba** [comment]
@jbruns2019 Lets clarify what you are seeing, starting with the simple so I can try to reproduce or see if its a simple usage error.

- run this and put output here:
```powershell
## Get profile we are working with
Get-KeePassDatabaseConfiguration -DatabaseProfileName 'KeyAndMasterKeyDB'
```
- your keepass database uses both a key file and a master key password, is that correct?
- when did this start? 
- did this work before and it just stopped?
- what version of the module are you running?
```powershell
## Get version
Import-Module 'PoShKeePass'
Get-Module 'PoShKeePass'
```

**Comment by jbruns2019** [comment]
DatabasePath       : C:\Users\u0132130\Dropbox\MyKeePassDB.kdbx
Default            : False
Name               : KeyAndMasterKeyDB
UseMasterKey       : False
KeyPath            : C:\Users\u0132130\Documents\MyKeePassDB.key
AuthenticationType : Key
UseNetworkAccount  : False


  *   your keepass database uses both a key file and a master key password, is that correct?
     *   yes
  *   when did this start?
     *   After downloading your code 2 days ago and I tried it
  *   did this work before and it just stopped?
     *   Never tried until 2 days ago
  *   what version of the module are you running?
     *   2.1.3.0


-Joe B.

**Comment by jkdba** [comment]
Great if you use a key file and password to auth you profile should look like this:

DatabasePath       : C:\Users\u0132130\Dropbox\MyKeePassDB.kdbx
Default            : False
Name               : KeyAndMasterKeyDB
UseMasterKey       : **True**
KeyPath            : C:\Users\u0132130\Documents\MyKeePassDB.key
AuthenticationType : Key
UseNetworkAccount  : False

You can also set a KeePassDatabaseConfigurationProfile as the default so you don't have to specify the profile on every call. To do this when creating the profile specify the '-Default' parameter when creating the profile.

to fix it run this:

```powershell
## Remove current profile and create a new one with the -UseMasterKey parameter 
PS> Remove-KeePassDatabaseConfiguration -DatabaseProfileName 'KeyAndMasterKeyDB' -force
PS> New-KeePassDatabaseConfiguration -DatabaseProfileName 'KeyAndMasterKeyDB' -DatabasePath 'C:\Users\u0132130\Dropbox\MyKeePassDB.kdbx' -KeyPath 'C:\Users\u0132130\Documents\MyKeePassDB.key' -UseMasterKey
# Or if you want it to be the default
PS> New-KeePassDatabaseConfiguration -DatabaseProfileName 'KeyAndMasterKeyDB' -DatabasePath 'C:\Users\u0132130\Dropbox\MyKeePassDB.kdbx' -KeyPath 'C:\Users\u0132130\Documents\MyKeePassDB.key' -UseMasterKey -Default
```

the to make calls you have two choices

1. Enter Password when prompted at each call
```powershell
PS> Get-KeePassEntry -DatabaseProfileName 'KeyAndMasterKeyDB' -AsPlainText
KeePass Password: *****
# Or if you made it your default profile
PS> Get-KeePassEntry -AsPlainText
KeePass Password: *****
```
2. Pass a powershell credential object to the `-MasterKey` parameter
```powershell
# get your master key password in a secure credential object, note the username does not matter
$masterkey = Get-Credential -UserName 'keepass' -Message 'enter masterkey password'
# or it also support a secureString type for the master key so you could do this as well
$masterkey = ConvertTo-SecureString -String 'MyPassword' -AsPlainText -Force

# pass your master key
Get-KeePassEntry -DatabaseProfileName 'KeyAndMasterKeyDB' -AsPlainText -MasterKey $masterkey
# Or if you made it your default profile
Get-KeePassEntry -AsPlainText -MasterKey $masterkey
```

**Comment by jbruns2019** [comment]
Much better, thank you!

-Joe B.

**Comment by jkdba** [comment]
Not a problem!

**Comment by marayas** [comment]
Can you set up key path as false?
