### ISSUE TITLE
How to change DatabasePath in an existing DatabaseConfiguration

### ISSUE THREAD

**Issue by Remi-PAULEAU** [PSKeePass/PoShKeePass#167]
Hi,

I want to change DatabasePath. I suppose I must use "Update-KeePassDatabaseConfiguration" but I don't understand How.

Update-KeePassDatabaseConfiguration -DatabaseProfileName "MyDatabaseProfileName.kdbx" -DatabasePath "X:\My\NewShare\MyDatabaseProfileName.kdbx.kdbx"

Error :
"Update-KeePassDatabaseConfiguration: The parameter set can not be resolved using the specified named parameters."

Regards,

**Comment by jkdba** [comment]
Hi, Thanks for reaching out, I tested as well and it appears to be broken.

While I fix this here are some workarounds:

### 1. Edit the xml configuration file directly:
This global variable has the path to the configuration file
```powershell
$Global:KeePassConfigurationFile
```
Edit this file, find the old path and replace with the new, save and done.

### 2. Remove the profile and recreate it with the new path.
```powershell
Remove-KeePassDatabaseConfiguration -DatabaseProfileName "MyDatabaseProfileName.kdbx"
New-KeePassDatabaseConfiguration -DatabaseProfileName "MyDatabaseProfileName.kdbx" <your other parameters>
```

**Comment by Remi-PAULEAU** [comment]
Thanks !

I'll change the path in my xml configuration here : 
"C:\Program Files\WindowsPowerShell\Modules\PoShKeePass\2.1.3.0\KeePassConfiguration.xml"

Thanks again =D
