### ISSUE TITLE
'Remove-KeePassDatabaseConfiguration' always asks for confirmation

### ISSUE THREAD

**Issue by DenisNedl** [PSKeePass/PoShKeePass#184]
Hi!
I'm using following configuration:
* Powershell: 5.1.17134.858
* PoShKeePass: 2.1.3.0
* KeePass: 2.4.1

I'm currently writing a script with loads of Pester tests. Everything works fine, but it is a little tedious to execute.
Reason is, that _"Remove-KeePassDatabaseConfiguration"_ always asks for confirmation. No Matter if I'm using _"-Confirm"_ or not.
As I'm always cleaning up the KPDBConfig after each test, and there are lots of them, I have to confirm a lot.
Thanks in advance for a hint how to solve this!

Best regards
Denis

**Comment by ClaudioESSilva** [comment]
Hi @DenisNedl ,

Just to be sure are you using `-Confirm:$false`?

**Comment by DenisNedl** [comment]
Hi Claudio,
sorry for the late reply, but I didn't get a notification...
Nope, I thought a switch parameter will be set to $false if not added in function call.
It works now.

Thanks a lot!

**Comment by ClaudioESSilva** [comment]
That assumption is true. However depending on the ConfirmationImpact level, it can pop-up. 
In that cases when you want unattended scripts to run you should force it to false.

**Comment by DenisNedl** [comment]
Thanks a lot!
