### ISSUE TITLE
Get all entries and use standard where-object/select-object cmdlets to filter

### ISSUE THREAD

**Issue by Ian2020** [PSKeePass/PoShKeePass#31]
What do you think of the idea to change the Get-KeePassEntry cmdlet so it does not require group and title? Then I can use standard PS cmdlets for filtering after I have got all entries. This would enable me to search databases for entries without expiries, weak passwords, e.g.

`Get-KeePassEntry | Where-Object { $_.Expiry -eq $null }`

Am happy to submit PR for this if you think it would be beneficial to the project.

**Comment by jkdba** [comment]
@Ian2020 That is definitely the direction this is heading. My only concern would be return the sensitive data in plain text (namely the passwords).

For this I could leave them in their KeePass Protected string state then force the user to convert them using another cmdlet  via the pipeline, or I could add a -force/-asplaintext flag to return them as plain text.

As far as submitting a PR, feel free just be sure to use the dev branch and see if you can integrate some of the base functions I have already written. (They are denoted by the keepass acronym Verb-KP..)

**Comment by jkdba** [comment]
@Ian2020 This functionality is now in the dev branch. Note there have been some major changes to the code. I will be posting documentation soon on how to use the front end functions such as Get,Set,New-KeePassEntry.

`Get-KeePassEntry -DatabaseProfileName 'A DATABASE PROFILE' -AsPlainText`

**Comment by jkdba** [comment]
Added to master.
