### ISSUE TITLE
Include Pester test

### ISSUE THREAD

**Issue by chritea** [PSKeePass/PoShKeePass#4]
Pester Tests will use a sample keepass databases.

- [x] Create Sample Databases for different authentication testing.
- [x] Create Pester tests
- [ ] Setup Github to execute pester tests upon commit/pull request.

**Comment by jkdba** [comment]
I found this really good series of articles on using, setting up, and executing pester tests [here](https://blogs.technet.microsoft.com/heyscriptingguy/2015/12/14/what-is-pester-and-why-should-i-care/).

I agree its a great idea to do this however, it well definitely take a good amount of time to do it right as we already have a good amount of code. So there will be lots of tests to create.

So I recommend you read though those articles and lets come up with how we want to do these tests, like to what level of detail/unit.

**Comment by jkdba** [comment]
@chritea 

Ok another update on this for in your downtime, I highly recommend the Pester Test Presentation by June Blender recorded [here](https://www.youtube.com/watch?v=gssAtCeMOoo), [Github](https://github.com/psconfeu/2016/tree/master/June%20Blender/RealWorldPesterTDD)

**Comment by jkdba** [comment]
Added the beginning of pester tests.

**Comment by jkdba** [comment]
Created initial set of pester tests total of 90 tests covering the main exposed functions and some non exposed functions.

**Comment by jkdba** [comment]
Will Create a New Issue for setting up Continuous integration using Appveyor
