### ISSUE TITLE
Add -AsPSCredential flag to Get-KeePassEntry

### ISSUE THREAD

**Issue by jkdba** [PSKeePass/PoShKeePass#53]

**Comment by Dan-Raoul** [comment]
If I'm understanding this correctly, this would add the option to pass along a KeePass-entry to e.g. Get-Credential/instead of Get-Credential, so I could use this in scripting a login to e.g. MSOnline, Exchange Online Powershell quickly? That would in that case be awesome.

**Comment by jkdba** [comment]
@Dan-Raoul that is correct if you want to do this now you can by building the PSCredential object yourself, albeit a pain if you are trying to quickly do something on the command line.

This is how you could build the credential object.

```PowerShell
## Note the password must be of type securestring.
$SecurePassword = ConvertTo-SecureString -String (Get-KeePassEntry -AsPlainText <other options>| Where-Object { $_.UserName -eq 'Myuser' } ).Password -AsPlainText -Force
[PSCredential] $Credential = New-Object -TypeName PSCredential -ArgumentList "Domain\UserName",$SecurePassword 
``` 

I will definitely make sure this makes it in the next release. 

If there is anything else you would like to see please upvote a current issue or create a new issue with the request. 

Thank for your feedback.
