### ISSUE TITLE
Allow for User Specified API Version

### ISSUE THREAD

**Issue by jkdba** [PSKeePass/PoShKeePass#64]
Potentially this could be saved in the config, as well as  a parameter to `Import-KPLibrary`.

This will require that the function `Import-KPLibrary` to be exposed to the user.

**Comment by Ninjigen** [comment]
In my opinion, the user should be able to specify a custom installation path (path to KeePass.exe) and set it in the profile. Packaging the dll in case the user doesn't have a working installation or does not want to use a different version is necessary, though

**Comment by jkdba** [comment]
I think that is fine but we will need to do a version check and make sure that everything we do is supported by the various versions.

**Comment by jkdba** [comment]
dup of #118, will close and track there.
