### ISSUE TITLE
Merge the two different Connection Functions

### ISSUE THREAD

**Issue by jkdba** [PSKeePass/PoShKeePass#67]
Currently there are two functions that perform different steps in getting a KeePass database Connection.

`Get-KPConnection`
`Invoke-KPConnection`

As discussed this needs to be merged into one function called `New-KPConnection`.

This function will handle both steps of the connection process.

**Comment by Ninjigen** [comment]
Should return an open keepass database connection
Should handle the following methods of authentication ; 
 - from profile
 - from a combination of Password and/or Keyfile and/or WindowsAccount
 - from a combination of Credential and/or Keyfile and/or Windows Account ? (is it necessary ?)

Returns a Keepass database object

Should be private

**Comment by jkdba** [comment]
@Ninjigen  can you be more specific with your question here ?

**Comment by jkdba** [comment]
The New-KPConneciton Function Still needs some work.

1. It still does not support using a master key, key file and windows account as a triple authentication method.
2. Needs another Parameter Set for the MasterKey and Credential Options. As it is confusing that you can specify both when the end result is that it is the same thing. If not another parameter set then let's consolidate the two parameters and use a ValidateScript Attribute to validate the two Credential types (Cred and secure string). Then we can use the type to choose how to parse the passed cred.

**Comment by jkdba** [comment]
Also, the logic allows for both the master key and cred to be added to the composite key, which will also break if the user specifies both parameters out of confusion.

**Comment by jkdba** [comment]
Ok, Fixed number 1 mentioned above the order in which the key is built is important.

**Comment by jkdba** [comment]
Made these changes in the last commit to the Dev branch:

1. Added Default ParameterSet
2. Removed Credential Parameter.
3. Changed Masterkey Parameter to Object Type. Allow Nulls, Performs
type validation in function and checks for Type SecureString and
PSCredential.
4. Reordered and added Positions to parameters in a more logical way.
5. Added Inline Comments.
6. Add More specific logic in regards to parameter set being used to make
the code more structured and easier to update in the future.
7.  Split UseMasterKey Logic between parameter sets for less complex
easier to manage code.
8.  The user will only get prompted for the master key (via Credential
prompt) if they specify a Profile that requires one without specifying
the MasterKey Parameter.
9. Updated format to be consistent with rest of module

Still to be completed:

Finish writing Pester Tests to test all functionality of the module.

**Comment by jkdba** [comment]
tests have been created.

**Comment by jkdba** [comment]
completed in #107
