### ISSUE TITLE
Fix `Get-Help ConvertTo-KPPSObject -examples` entry

### ISSUE THREAD

**Issue by erichiller** [PSKeePass/PoShKeePass#91]
I believe there is some antiquated code that needs updating here:

`Get-Help ConvertTo-KPPSObject -examples`

Under the second example:

```powershell

Example #2

    PS>Get-KeePassEntry -KeePassonnection $DB -UserName "AUserName" | ConvertTo-KeePassPsObject
```

The flags `-KeePassonnection` and `-UserName` do not exist (although a `-UserName` may be nice to implement)

**Comment by jkdba** [comment]
Thanks for finding this.

I removed the `-UserName` option along with some others a while ago to allow the user to filter how they want in a more PowerShell way. That is using `Where-Object` and `Select-Object` type commands.

I don't see the harm in adding this functionality back in, as it allows for a more secure method of performing a look up given that the lookup does not return all or most entries. See new issue #93 .

**Comment by erichiller** [comment]
Thanks, much appreciated, I'll track that issue.
